<html>
<head>
<title>Practical Python: Try, Except, and Assert</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">实用Python: Try、Except和Assert</h1>
<blockquote>原文：<a href="https://towardsdatascience.com/practical-python-try-except-and-assert-7117355ccaab?source=collection_archive---------7-----------------------#2020-11-14">https://towardsdatascience.com/practical-python-try-except-and-assert-7117355ccaab?source=collection_archive---------7-----------------------#2020-11-14</a></blockquote><div><div class="fc ih ii ij ik il"/><div class="im in io ip iq"><div class=""/><div class=""><h2 id="cad1" class="pw-subtitle-paragraph jq is it bd b jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh dk translated">综合实践指南</h2></div><figure class="kj kk kl km gt kn gh gi paragraph-image"><div role="button" tabindex="0" class="ko kp di kq bf kr"><div class="gh gi ki"><img src="../Images/c09cb31f80b62506883c517ff90d99db.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*vQNfueeWdxaoCyWDWUSS8w.jpeg"/></div></div><p class="ku kv gj gh gi kw kx bd b be z dk translated">威廉·戴尼奥在<a class="ae ky" href="https://unsplash.com/s/photos/try?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上拍摄的照片</p></figure><p id="4191" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">每个软件程序员的梦想都是写一个运行流畅的程序。然而，开始时通常不是这样。如果出现错误，代码的执行将会停止。</p><p id="70b0" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">意外情况或条件可能会导致错误。Python将这些情况视为异常，并根据异常的类型引发不同种类的错误。</p><p id="c3ce" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">ValueError、TypeError、AttributeError和SyntaxError是这些异常的一些示例。好在Python还提供了处理异常的方法。</p><p id="8074" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">考虑下面的代码，它要求用户输入一个数字，并打印该数字的平方。</p><pre class="kj kk kl km gt lv lw lx ly aw lz bi"><span id="9c73" class="ma mb it lw b gy mc md l me mf">a = int(input("Please enter a number: "))</span><span id="b41a" class="ma mb it lw b gy mg md l me mf">print(f'{a} squared is {a*a}')</span></pre><p id="a44d" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">只要输入的是数字，它就能正常工作。但是，如果用户输入一个字符串，python将引发一个ValueError:</p><figure class="kj kk kl km gt kn gh gi paragraph-image"><div class="gh gi mh"><img src="../Images/d39f9e79acdbac05ffba6de701d053ee.png" data-original-src="https://miro.medium.com/v2/resize:fit:1118/format:webp/1*CjcoUcM19Mt_n3UrjAHiSA.png"/></div><p class="ku kv gj gh gi kw kx bd b be z dk translated">(图片由作者提供)</p></figure><p id="9a4e" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">我们可以在代码中实现一个try-except块来更好地处理这个异常。例如，我们可以向用户返回一个更简单的错误消息，或者要求他们再输入一次。</p><pre class="kj kk kl km gt lv lw lx ly aw lz bi"><span id="f174" class="ma mb it lw b gy mc md l me mf">try:<br/>   a = int(input("Please enter a number: "))<br/>   print(f'{a} squared is {a*a}')<br/>except:<br/>   print("Wrong input type! You must enter a number!")</span></pre><p id="4f05" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">在上面的例子中，代码更清楚地通知用户错误。</p><p id="2460" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">如果由于try块中的代码引发了异常，则执行将继续except块中的语句。因此，如何处理异常取决于程序员。</p><p id="a39c" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">普通的try-except块将捕捉任何类型的错误。但是，我们可以更具体一些。例如，我们可能只对特定类型的错误感兴趣，或者希望以不同的方式处理不同类型的错误。</p><p id="2f06" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">可以用except语句指定错误的类型。考虑下面的代码，它要求用户从列表中输入一个数字。然后，它根据输入从字典中返回一个名字。</p><pre class="kj kk kl km gt lv lw lx ly aw lz bi"><span id="2f8b" class="ma mb it lw b gy mc md l me mf">dict_a = {1:'Max', 2:'Ashley', 3:'John'}</span><span id="57d9" class="ma mb it lw b gy mg md l me mf">number = int(input(f'Pick a number from the list: {list(dict_a.keys())}'))</span></pre><p id="fd28" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">如果用户输入一个不在给定列表中的数字，我们将得到一个KeyError。如果输入不是一个数字，我们将得到一个ValueError。我们可以使用两个except语句来处理这两种情况。</p><pre class="kj kk kl km gt lv lw lx ly aw lz bi"><span id="2083" class="ma mb it lw b gy mc md l me mf">try:<br/>   dict_a = {1:'Max', 2:'Ashley', 3:'John'}<br/>   number = int(input(f'Pick a number from the list: <br/>   {list(dict_a.keys())}'))<br/>   print(dict_a[number])<br/>except KeyError:<br/>   print(f'{number} is not in the list')<br/>except ValueError:<br/>   print('You must enter a number!')</span></pre><figure class="kj kk kl km gt kn gh gi paragraph-image"><div role="button" tabindex="0" class="ko kp di kq bf kr"><div class="gh gi mi"><img src="../Images/78e1006cb2f44d98054bd18701b7e909.png" data-original-src="https://miro.medium.com/v2/resize:fit:1270/format:webp/1*OeITddyteRycI8EQq6FT4Q.png"/></div></div><p class="ku kv gj gh gi kw kx bd b be z dk translated">(图片由作者提供)</p></figure><p id="2a0c" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">Python还允许引发自己的异常。这有点像定制默认异常。raise关键字和错误类型一起用于创建您自己的异常。</p><pre class="kj kk kl km gt lv lw lx ly aw lz bi"><span id="4489" class="ma mb it lw b gy mc md l me mf">try:<br/>   a = int(input("Please enter a number: "))<br/>   print(f'{a} squared is {a*a}')<br/>except:<br/>   raise ValueError("You must enter a number!")</span></pre><p id="ec26" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">以下是非数字输入情况下的错误消息。</p><pre class="kj kk kl km gt lv lw lx ly aw lz bi"><span id="5489" class="ma mb it lw b gy mc md l me mf">ValueError: You must enter a number!</span></pre><p id="bcdc" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">让我们再做一个例子，展示如何在函数中使用try-except块。</p><p id="d669" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">avg_value函数返回一组数字的平均值。</p><pre class="kj kk kl km gt lv lw lx ly aw lz bi"><span id="aba3" class="ma mb it lw b gy mc md l me mf">a = [1, 2, 3]</span><span id="262e" class="ma mb it lw b gy mg md l me mf">def avg_value(lst):<br/>   avg = sum(lst) / len(lst)<br/>   return avg</span><span id="f92f" class="ma mb it lw b gy mg md l me mf">print(avg_value(a))<br/>2</span></pre><p id="b5c5" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">如果我们传递一个空列表给这个函数，它会给出一个ZeroDivisionError，因为空列表的长度是零。</p><p id="3c64" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">我们可以在函数中实现一个try-except块来处理这个异常。</p><pre class="kj kk kl km gt lv lw lx ly aw lz bi"><span id="78e8" class="ma mb it lw b gy mc md l me mf">def avg_value(lst):<br/>   try:<br/>      avg = sum(lst) / len(lst)<br/>      return avg<br/>   except:<br/>      print('Warning: Empty list')<br/>      return 0</span></pre><p id="1c09" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">如果列表为空，该函数将打印一条警告并返回0。</p><pre class="kj kk kl km gt lv lw lx ly aw lz bi"><span id="ffa6" class="ma mb it lw b gy mc md l me mf">a = []</span><span id="a826" class="ma mb it lw b gy mg md l me mf">print(avg_value(a))<br/>Warning: Empty list<br/>0</span></pre></div><div class="ab cl mj mk hx ml" role="separator"><span class="mm bw bk mn mo mp"/><span class="mm bw bk mn mo mp"/><span class="mm bw bk mn mo"/></div><div class="im in io ip iq"><p id="a2c0" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">try和except块用于处理异常。断言用于确保条件符合函数的要求。</p><p id="5875" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">如果断言为假，则函数不继续。因此，断言可以是防御性编程的一个例子。程序员正在确保一切都如预期的那样。</p><p id="1800" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">让我们在avg_value函数中实现assert。我们必须确保该列表不为空。</p><pre class="kj kk kl km gt lv lw lx ly aw lz bi"><span id="b44e" class="ma mb it lw b gy mc md l me mf">def avg_value(lst):<br/>   assert not len(lst) == 0, 'No values'<br/>   avg = sum(lst) / len(lst)<br/>   return avg</span></pre><p id="80f2" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">如果列表的长度为零，函数立即终止。否则，它会一直持续到结束。</p><p id="0084" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">如果assert语句中的条件为false，将引发AssertionError:</p><pre class="kj kk kl km gt lv lw lx ly aw lz bi"><span id="5459" class="ma mb it lw b gy mc md l me mf">a = []<br/>print(avg_value(a))<br/>AssertionError: No values</span></pre><p id="55d3" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">assert对于发现代码中的错误非常有用。因此，它们可以用来支持测试。</p></div><div class="ab cl mj mk hx ml" role="separator"><span class="mm bw bk mn mo mp"/><span class="mm bw bk mn mo mp"/><span class="mm bw bk mn mo"/></div><div class="im in io ip iq"><h2 id="894a" class="ma mb it bd mq mr ms dn mt mu mv dp mw li mx my mz lm na nb nc lq nd ne nf ng bi translated">结论</h2><p id="8782" class="pw-post-body-paragraph kz la it lb b lc nh ju le lf ni jx lh li nj lk ll lm nk lo lp lq nl ls lt lu im bi translated">我们已经介绍了如何在代码中实现try、except和assert。它们在很多情况下都派上了用场，因为很可能会遇到不符合预期的情况。</p><p id="75ac" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">Try、except和assert为程序员提供了对代码的更多控制和监督。他们能很好地发现和处理异常。</p><p id="715d" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">感谢您的阅读。如果您有任何反馈，请告诉我。</p></div></div>    
</body>
</html>