<html>
<head>
<title>Python: Writing Custom Exceptions is easier than you might think</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">Python:编写定制异常比您想象的要简单</h1>
<blockquote>原文：<a href="https://towardsdatascience.com/python-writing-custom-exceptions-is-easier-than-you-might-think-14df327e503e?source=collection_archive---------47-----------------------#2020-06-18">https://towardsdatascience.com/python-writing-custom-exceptions-is-easier-than-you-might-think-14df327e503e?source=collection_archive---------47-----------------------#2020-06-18</a></blockquote><div><div class="fc ih ii ij ik il"/><div class="im in io ip iq"><div class=""/><div class=""><h2 id="80ac" class="pw-subtitle-paragraph jq is it bd b jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh dk translated">Python提供了许多内置的异常，然而，有时自己创建异常更有意义</h2></div><figure class="kj kk kl km gt kn gh gi paragraph-image"><div role="button" tabindex="0" class="ko kp di kq bf kr"><div class="gh gi ki"><img src="../Images/fa5ec70b98bab4212b054cae87c05783.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*r_BndT7DE3FNmwzBMn8DkQ.png"/></div></div></figure><p id="1495" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">在Python中处理运行时错误非常容易。您只需将代码放在try-except块中，并处理Python提供的许多内置异常类型中的异常。下面是一个用Python处理简单错误的例子。</p><pre class="kj kk kl km gt lq lr ls lt aw lu bi"><span id="2e32" class="lv lw it lr b gy lx ly l lz ma">number_followers = 40<br/>"Hello, My name is Shivam and I have " + number_followers + " followers on Medium."</span></pre><p id="3063" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">这段代码会产生一个错误，特别是TypeError，因为+运算符不能将字符串和整数类型相加，我已经在关于魔法方法的<a class="ae mb" href="https://medium.com/dataseries/using-pythons-magic-methods-to-compare-tesla-and-ford-8dd9a4fcbe1e" rel="noopener">独立文章中解释了这些运算符是如何工作的，如果你想阅读相关内容，请查看。让我们试一试这段代码。</a></p><pre class="kj kk kl km gt lq lr ls lt aw lu bi"><span id="38b8" class="lv lw it lr b gy lx ly l lz ma">try:<br/>   number_followers = 40<br/>   "My name is Shivam and I have " + number_followers + "on medium."<br/>except TypeError:<br/>   print("A string and integer cannot be concatenated")</span></pre><p id="25d1" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">看，简单明了，但是只有我们需要写代码来连接一个字符串和一个整数。在现实生活中，管理大型代码库，许多团队使用您的代码，引发您的代码中出现的异常，这不是一个好的做法。</p><p id="9df6" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">尽管Python提供了许多内置的异常类型，但有时我们不得不编写定制的异常来满足我们的目的。让我们假设一个程序来计算一个圆的面积，周长和其他一些东西，我们为此创建一个类圆。</p><figure class="kj kk kl km gt kn"><div class="bz fp l di"><div class="mc md l"/></div></figure><p id="c89a" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">编写新的定制异常非常简单。我们需要从内置模块中扩展异常类。</p><figure class="kj kk kl km gt kn"><div class="bz fp l di"><div class="mc md l"/></div><p class="me mf gj gh gi mg mh bd b be z dk translated">CircleException现在可以像任何其他内置异常一样被引发</p></figure><p id="4f11" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">现在，我们可以在代码中出现错误的情况下抛出这个异常，而不必用确切的错误来麻烦客户团队。这样，客户端团队只需处理CircleException，无论Circle类中有什么错误，都会引发该异常。除此之外，我们还可以在客户端修改错误消息，以获得更健壮的日志记录系统。</p><figure class="kj kk kl km gt kn"><div class="bz fp l di"><div class="mc md l"/></div></figure><p id="de01" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">在客户端，我们只需要捕捉CircleException类型。</p><p id="d164" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">所以与其这样，</p><pre class="kj kk kl km gt lq lr ls lt aw lu bi"><span id="283e" class="lv lw it lr b gy lx ly l lz ma">s = Circle(5)</span><span id="db15" class="lv lw it lr b gy mi ly l lz ma">try:<br/>    s.area()<br/>except TypeError:<br/>    print("Something wrong with the values sent")<br/>except AttributeError:<br/>    print("Something wrong with the attributes of the class")<br/>except KeyError:<br/>    print("Something went wrong with the keys in shape class")</span></pre><p id="9117" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">我们将只处理CircleException，这样客户端就不必处理所有可能与我们的CircleClass有关的错误。下面大概是这样的。</p><figure class="kj kk kl km gt kn"><div class="bz fp l di"><div class="mc md l"/></div></figure><p id="bd67" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">我们还可以修改它，并通过引入实例变量向自定义异常添加属性。</p><figure class="kj kk kl km gt kn"><div class="bz fp l di"><div class="mc md l"/></div></figure><p id="3086" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">让我们通过在Circle类中引发CircleException时初始化方法名变量来使用它。</p><figure class="kj kk kl km gt kn"><div class="bz fp l di"><div class="mc md l"/></div></figure><p id="9a90" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">现在，客户端将所有的方法放在一个try-except下，将能够获得准确的错误消息，该错误消息可以记录在日志系统中。</p><pre class="kj kk kl km gt lq lr ls lt aw lu bi"><span id="dc4a" class="lv lw it lr b gy lx ly l lz ma">s = Shape(shape_name='circle', radius=5)</span><span id="c5fe" class="lv lw it lr b gy mi ly l lz ma">try:</span><span id="95d7" class="lv lw it lr b gy mi ly l lz ma">    area = s.area()<br/>    circumference = s.circumference()<br/>    diameter = s.diameter()</span><span id="e0a6" class="lv lw it lr b gy mi ly l lz ma">except CircleException as e:<br/>    print(e)</span></pre><p id="1138" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">让我们假设Circle类的area方法出了问题，没有权限修改Circle类的客户端可以很好地处理它，输出将是这样的。</p><figure class="kj kk kl km gt kn gh gi paragraph-image"><div role="button" tabindex="0" class="ko kp di kq bf kr"><div class="gh gi mj"><img src="../Images/8287da2d3e48fd20974b5e5a7b857572.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*Y_fOHhDP2MjGPAH1Od9N-A.png"/></div></div></figure><p id="6abf" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">本文帮助您理解如何以及为什么用Python编写自定义异常。在很多情况下，编写自定义异常比内置异常更有意义，读完本文后，我希望您对自定义异常有更好的理解，并知道如何抓住这些机会。</p></div><div class="ab cl mk ml hx mm" role="separator"><span class="mn bw bk mo mp mq"/><span class="mn bw bk mo mp mq"/><span class="mn bw bk mo mp"/></div><div class="im in io ip iq"><p id="3b21" class="pw-post-body-paragraph ku kv it kw b kx ky ju kz la lb jx lc ld le lf lg lh li lj lk ll lm ln lo lp im bi translated">如果你喜欢这篇文章并学到了一些东西，请在twitter和medium上关注我，阅读更多类似的内容。我写关于Python，数据科学，ML，AI等等。</p></div></div>    
</body>
</html>